# Configuration file for the Sphinx documentation builder.
#
# For the full list of built-in configuration values, see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

import sys
from importlib.metadata import PackageNotFoundError
from importlib.metadata import version as metadata_version
from pathlib import Path

# -- Path setup --------------------------------------------------------------

SPHINX = Path(__file__).parent.absolute()
DOCS = SPHINX.parent
ROOT = DOCS.parent

sys.path.insert(0, str(SPHINX))
sys.path.insert(0, str(DOCS))
sys.path.insert(0, str(ROOT))

# -- Version reading ---------------------------------------------------------


def get_version() -> str:
    """Get project version, preferentially from installed package."""
    # Method 1: Try to read from installed package
    try:
        return metadata_version("pyformatjson")
    except (PackageNotFoundError, ImportError):
        pass

    # Method 2: Read from pyproject.toml
    try:
        import tomllib
        pyproject_path = ROOT / "pyproject.toml"
        with open(pyproject_path, "rb") as f:
            data = tomllib.load(f)
            return data["tool"]["poetry"]["version"]  # pyproject.toml generated by Poetry
    except Exception as e:
        print(f"Warning: Could not read version, using fallback: {e}")
        return "0.1.0"


def get_major_minor_version(full_version: str) -> str:
    """Extract major.minor version from full version string."""
    try:
        parts = full_version.split('.')
        if len(parts) >= 2:
            return '.'.join(parts[:2])
        return full_version
    except Exception:
        return "0.1"


# -- Project information -----------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#project-information

project = 'pyformatjson'
author = 'NextAI'
copyright = '2025, NextAI'

release = get_version()
version = get_major_minor_version(release)

# -- General configuration ---------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#general-configuration

extensions = ['sphinx.ext.autodoc',
              'sphinx.ext.napoleon',
              'sphinx.ext.viewcode',
              'sphinx_copybutton',]

# Napoleon settings
napoleon_google_docstring = True
napoleon_numpy_docstring = False

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ['.DS_Store']

# -- Options for HTML output -------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-html-output

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'sphinx_rtd_theme'

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
# html_static_path = ['_static']
html_static_path = []
